name: 'Setup Node.js and pnpm'
description: 'Setup Node.js, pnpm, and install dependencies with caching'

runs:
  using: 'composite'
  steps:
    - name: 📦 Setup pnpm and install
      uses: pnpm/action-setup@v4
      with:
        cache: true
        run_install: true
